### PR TITLE
Some users shit, some friends shit

### PR DESCRIPTION
**Pull request by gavinschriver**
1. `git fetch --all` or if you already have this branch from fetching, make sure you 
2. `git checkout gs-friendsComponents
3. Serve the page and fire that baby up. Fill in a new user name and PW and smash that go button to see an 'add friend' button. the 'nut lives.
4. Refresh and be amazed that you're still logged in. also check the console you should the ID of the active user 
5. Open new tab and log in with those new credentials. rinse/repeat
6. make sure my users and friends data providers are there. oh along with directories within /scripts for /chat, /events, /friends, /news and /weather
7. Create at least 2 users, then when you're logged in as one, click "add a friend" and enter another username EXACTLY (only works like this now, no validation yet so dont mess around lol) and click "save friend" to see their name in friends list (should create friend object as well) along w delete button. decide you hate them and click delete button, verify it disappears from DOM and also that friends object goes byebye from database

### CODE REVIEW

**Comment by Michaelr-Tyler** [comment]
Everything works!

**Comment by travisbrigman** [comment]
NICE!

bitmoji

**Review by travisbrigman — APPROVED** [review]
nice!

bitmoji

**Review by ghost — APPROVED** [review]
Let me learn!

**Pull request merged**
